// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/cleverhu/task-cicd/pkg/client/clientset/versioned/typed/task/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCicdV1alpha1 struct {
	*testing.Fake
}

func (c *FakeCicdV1alpha1) Tasks(namespace string) v1alpha1.TaskInterface {
	return &FakeTasks{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCicdV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
