// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// TaskListerExpansion allows custom methods to be added to
// TaskLister.
type TaskListerExpansion interface{}

// TaskNamespaceListerExpansion allows custom methods to be added to
// TaskNamespaceLister.
type TaskNamespaceListerExpansion interface{}
